import { SimulationData } from './types';

export const SIMULATION_DATA: SimulationData = {
  "version": "1.4",
  "topics": [
    {
      "topic": "Vehicle Cost and Value",
      "entries": [
        { "keyword": "EV bike prices Vietnam", "prompt": "What is the typical purchase price range for various electric two-wheelers available in the market?" },
        { "keyword": "Electric motorcycle maintenance cost", "prompt": "Which electric bike models come with a swappable battery option that affects the upfront cost?" },
        { "keyword": "Government incentives EV Vietnam", "prompt": "Are there any specific electric motorbikes that offer flexible payment plans or financing options?" },
        { "keyword": "Resale value electric motorcycle", "prompt": "What is the average yearly cost for scheduled maintenance for different electric scooter models?" },
        { "keyword": "Electric bike warranty comparison", "prompt": "What depreciation rate is commonly observed for various electric bikes after three years of ownership?" },
        { "keyword": "Cheap electric scooter Vietnam", "prompt": "What are the most affordable electric scooter models available for students in Vietnam?" },
        { "keyword": "VinFast Klara price 2024", "prompt": "How does the pricing of the latest VinFast Klara compare to its petrol equivalents?" },
        { "keyword": "Dat Bike Weaver++ cost", "prompt": "Is the Dat Bike Weaver++ considered a budget-friendly option compared to other high-speed electric bikes?" },
        { "keyword": "Pega electric bike price list", "prompt": "Where can I find the official price list for Pega's current electric vehicle lineup?" },
        { "keyword": "Yadea electric scooter Vietnam price", "prompt": "Are there currently any promotional discounts for Yadea electric scooters in Hanoi?" },
        { "keyword": "Second hand electric motorbike", "prompt": "What is the market availability and typical price for used electric motorcycles in Ho Chi Minh City?" },
        { "keyword": "Installment plan electric scooter", "prompt": "Which banks offer 0% interest installment plans for purchasing electric motorbikes?" },
        { "keyword": "Cost of ownership EV vs Gas", "prompt": "How does the total cost of ownership over 5 years compare between an electric scooter and a Honda Vision?" },
        { "keyword": "Battery rental cost VinFast", "prompt": "What are the monthly subscription fees for VinFast battery rental packages?" },
        { "keyword": "Electric bike insurance cost", "prompt": "Is insurance for electric motorbikes cheaper or more expensive than for gasoline bikes?" },
        { "keyword": "Registration fee electric motorbike", "prompt": "How much is the registration fee for a new electric motorcycle in District 1?" },
        { "keyword": "Luxury electric motorcycle Vietnam", "prompt": "What are the premium electric motorcycle options available for high-end consumers?" },
        { "keyword": "Discount electric bike student", "prompt": "Do manufacturers offer specific discounts for university students buying electric bikes?" },
        { "keyword": "Trade-in petrol for electric", "prompt": "Are there any trade-in programs to swap an old petrol bike for a new electric one?" },
        { "keyword": "Honda electric scooter price", "prompt": "What is the expected launch price of Honda's upcoming electric scooter models in Vietnam?" },
        { "keyword": "Electric bike depreciation", "prompt": "Do electric bikes hold their value better than traditional scooters in the current market?" },
        { "keyword": "Hidden costs buying EV", "prompt": "Are there any hidden costs like charger installation or specialized gear when buying an EV bike?" },
        { "keyword": "Comparison EV prices 2025", "prompt": "How are EV prices projected to change in 2025 compared to 2024?" },
        { "keyword": "Used VinFast Ludo price", "prompt": "What is the going rate for a used VinFast Ludo in good condition?" },
        { "keyword": "Bank financing EV bike", "prompt": "Which banks provide the best interest rates for electric vehicle loans?" },
        { "keyword": "Cost of battery replacement", "prompt": "How much does it cost to replace the battery pack out of warranty?" },
        { "keyword": "Electricity cost per km", "prompt": "What is the calculated electricity cost per kilometer for a typical e-scooter?" },
        { "keyword": "Leasing electric motorbike", "prompt": "Are there options to lease electric motorbikes instead of buying them outright?" },
        { "keyword": "EV tax incentives 2024", "prompt": "Do tax incentives significantly lower the on-the-road price of EVs?" },
        { "keyword": "Dealer markup electric bike", "prompt": "Do dealers add markups to the manufacturer's suggested retail price?" },
        { "keyword": "Seasonal promotions EV", "prompt": "Are there specific times of year when EV prices drop due to promotions?" },
        { "keyword": "Total cost of ownership calculator", "prompt": "Is there a tool to calculate the TCO of an EV bike in Vietnam?" },
        { "keyword": "VinFast Evo 200 price", "prompt": "How much is the VinFast Evo 200 including battery?" },
        { "keyword": "VinFast Feliz S installment", "prompt": "What is the monthly installment for a Feliz S?" },
        { "keyword": "Yadea Odora price", "prompt": "Is the Yadea Odora cheaper than the VinFast Klara?" },
        { "keyword": "Dat Bike Quantum price", "prompt": "How much does the Dat Bike Quantum cost on the road?" },
        { "keyword": "Electric bike price under 20 million", "prompt": "What are the best electric bikes under 20 million VND?" },
        { "keyword": "Electric bike price under 30 million", "prompt": "Which bikes are available in the 25-30 million VND range?" },
        { "keyword": "High-end electric scooter price", "prompt": "How much do premium electric scooters cost?" },
        { "keyword": "Budget electric bike Vietnam", "prompt": "Where to find budget electric bikes?" },
        { "keyword": "Used Pega bike price", "prompt": "Price of used Pega bikes?" },
        { "keyword": "Selex Camel price", "prompt": "How much is the Selex Camel delivery bike?" },
        { "keyword": "Battery subscription vs buy", "prompt": "Is it better to rent or buy the battery?" },
        { "keyword": "Cost per charge VinFast", "prompt": "How much does it cost to fully charge a VinFast bike?" },
        { "keyword": "Maintenance cost comparison", "prompt": "Is EV maintenance cheaper than petrol?" },
        { "keyword": "Tire replacement cost EV", "prompt": "Cost of tires for EVs?" },
        { "keyword": "Brake pad cost EV", "prompt": "Cost of brake pads for EVs?" },
        { "keyword": "Resale value VinFast", "prompt": "Do VinFast bikes hold their value?" },
        { "keyword": "Depreciation curve EV", "prompt": "How fast do EVs depreciate?" },
        { "keyword": "Insurance premium EV", "prompt": "Are insurance premiums higher for EVs?" },
        { "keyword": "Loan interest rate EV", "prompt": "Interest rates for EV loans?" },
        { "keyword": "Registration tax EV 2024", "prompt": "Registration tax for EVs in 2024?" },
        { "keyword": "License plate fee EV", "prompt": "Fee for EV license plates?" },
        { "keyword": "Used Dat Bike price", "prompt": "Price of used Dat Bike?" },
        { "keyword": "Dibao electric bike price", "prompt": "Dibao price list?" },
        { "keyword": "Osakar electric bike price", "prompt": "Osakar price?" },
        { "keyword": "DK Bike price", "prompt": "DK Bike price?" },
        { "keyword": "Anbico electric bike price", "prompt": "Anbico price?" },
        { "keyword": "Beforei electric bike price", "prompt": "Beforei price?" },
        { "keyword": "JVC electric bike price", "prompt": "JVC price?" },
        { "keyword": "Nioshima electric bike price", "prompt": "Nioshima price?" },
        { "keyword": "Used electric bike Hanoi", "prompt": "Used EV Hanoi?" },
        { "keyword": "Used electric bike Da Nang", "prompt": "Used EV Da Nang?" },
        { "keyword": "Cheap EV for elderly", "prompt": "Cheap EV for old people?" },
        { "keyword": "Luxury EV price", "prompt": "Price of luxury EV?" },
        { "keyword": "Mid-range EV price", "prompt": "Price of mid-range EV?" },
        { "keyword": "Entry-level EV price", "prompt": "Price of entry-level EV?" },
        { "keyword": "EV price vs Honda Vision", "prompt": "Price comparison vs Vision?" },
        { "keyword": "EV price vs Honda Lead", "prompt": "Price comparison vs Lead?" },
        { "keyword": "EV price vs Honda Airblade", "prompt": "Price comparison vs Airblade?" },
        { "keyword": "EV price vs Yamaha Grande", "prompt": "Price comparison vs Grande?" },
        { "keyword": "VinFast battery promo", "prompt": "Battery promos?" },
        { "keyword": "Black Friday EV deals", "prompt": "Black Friday deals?" },
        { "keyword": "Tet holiday EV promo", "prompt": "Tet promos?" },
        { "keyword": "Back to school EV promo", "prompt": "Back to school promos?" },
        { "keyword": "Group buy discount EV", "prompt": "Group buy discounts?" },
        { "keyword": "Employee discount EV", "prompt": "Employee discounts?" },
        { "keyword": "Credit card installment 0%", "prompt": "0% installment credit card?" },
        { "keyword": "Home credit EV loan", "prompt": "Home Credit loan?" },
        { "keyword": "FE Credit EV loan", "prompt": "FE Credit loan?" },
        { "keyword": "HD Saison EV loan", "prompt": "HD Saison loan?" },
        { "keyword": "Running cost per month", "prompt": "Monthly running cost?" },
        { "keyword": "Parking fee electric bike", "prompt": "Parking fees?" },
        { "keyword": "Toll fee electric bike", "prompt": "Toll fees?" },
        { "keyword": "Charging cost per month", "prompt": "Monthly charging cost?" },
        { "keyword": "Replacement battery cost", "prompt": "Battery replacement cost?" }
      ]
    },
    {
      "topic": "Battery Performance and Charging",
      "entries": [
        { "keyword": "Electric scooter range Vietnam", "prompt": "What is the certified maximum travel distance on a single full charge for different electric bike models?" },
        { "keyword": "Battery charging stations Vietnam", "prompt": "Which electric scooters are compatible with fast-charging technologies currently available?" },
        { "keyword": "Long-range electric motorbike", "prompt": "How many battery swapping stations are operational for different electric bike ecosystems in major cities?" },
        { "keyword": "Fast charging EV bike technology", "prompt": "What is the estimated charging time from empty to full for various electric motorcycle batteries using a standard home outlet?" },
        { "keyword": "Motorcycle electric motor specs", "prompt": "Do any electric bike batteries come with specific temperature resistance ratings for hot weather?" },
        { "keyword": "VinFast charging station map", "prompt": "Where can I find a reliable map of all VinFast charging stations in Da Nang?" },
        { "keyword": "LFP battery lifespan", "prompt": "How many charge cycles can an LFP battery withstand before significant degradation?" },
        { "keyword": "Lithium-ion vs Lead-acid scooter", "prompt": "What are the performance differences between lithium-ion and lead-acid batteries for scooters?" },
        { "keyword": "Home charging electric bike safety", "prompt": "Is it safe to charge an electric motorbike battery inside an apartment overnight?" },
        { "keyword": "Public charging cost Vietnam", "prompt": "How much does it cost per kWh to charge an electric bike at a public station?" },
        { "keyword": "Selex Motors battery swapping", "prompt": "How does Selex Motors' battery swapping network function for delivery drivers?" },
        { "keyword": "Portable charger electric scooter", "prompt": "Are there lightweight portable chargers available for carrying in a backpack?" },
        { "keyword": "Battery water resistance IP67", "prompt": "Can electric bike batteries survive being submerged in water during flood season?" },
        { "keyword": "Dat Bike Weaver charging time", "prompt": "How long does it take to charge a Dat Bike Weaver using a super charger?" },
        { "keyword": "Battery degradation hot weather", "prompt": "Does the tropical heat in Vietnam significantly accelerate electric bike battery degradation?" },
        { "keyword": "Electric bike range 100km", "prompt": "Which electric scooter models offer a real-world range of over 100km per charge?" },
        { "keyword": "Smart battery management system", "prompt": "What features does a Smart BMS provide for monitoring battery health via a mobile app?" },
        { "keyword": "Removable battery electric bike", "prompt": "Which models feature easily removable batteries for charging in high-rise apartments?" },
        { "keyword": "Charging station compatibility", "prompt": "Can I charge a Yadea scooter at a VinFast charging post?" },
        { "keyword": "Emergency charging rescue", "prompt": "Are there services that deliver battery charge if I run out of power on the road?" },
        { "keyword": "Battery recycling Vietnam", "prompt": "What are the environmental policies for recycling old electric vehicle batteries in Vietnam?" },
        { "keyword": "Graphene battery technology", "prompt": "Are graphene batteries available in any electric scooters in Vietnam?" },
        { "keyword": "Voltage sag acceleration", "prompt": "Does the battery voltage drop significantly during hard acceleration?" },
        { "keyword": "Charging adapter types", "prompt": "What are the different types of charging adapters used for EV bikes?" },
        { "keyword": "Solar charging electric bike", "prompt": "Is it feasible to charge an electric bike using solar panels at home?" },
        { "keyword": "Battery warranty coverage", "prompt": "Does the battery warranty cover capacity loss below 70%?" },
        { "keyword": "Charging safety certification", "prompt": "Do the chargers come with safety certifications against overcharging?" },
        { "keyword": "Power bank for scooter", "prompt": "Can I use a large power bank to extend the range of my scooter?" },
        { "keyword": "Cold weather battery performance", "prompt": "Does battery performance drop in the colder months in Northern Vietnam?" },
        { "keyword": "Battery balancing", "prompt": "How often does the BMS perform cell balancing?" },
        { "keyword": "Overnight charging risks", "prompt": "What are the risks associated with leaving the bike plugged in overnight?" },
        { "keyword": "Real world range VinFast Evo", "prompt": "What is the actual range of VinFast Evo in city traffic?" },
        { "keyword": "Dat Bike Quantum range", "prompt": "Can the Dat Bike Quantum really go 270km?" },
        { "keyword": "Charging time 0-100%", "prompt": "How long for a full charge?" },
        { "keyword": "Fast charging stations Hanoi", "prompt": "Locations of fast chargers in Hanoi?" },
        { "keyword": "Battery swap cost Selex", "prompt": "Cost to swap a Selex battery?" },
        { "keyword": "Charging cable length", "prompt": "How long is the standard charging cable?" },
        { "keyword": "Extension cord charging", "prompt": "Is it safe to use an extension cord?" },
        { "keyword": "Battery weight removable", "prompt": "How heavy is the removable battery?" },
        { "keyword": "Spare battery cost", "prompt": "Cost of a spare battery?" },
        { "keyword": "Battery life cycles", "prompt": "Expected life cycles of the battery?" },
        { "keyword": "Recycling old batteries", "prompt": "Where to recycle old batteries?" },
        { "keyword": "Battery swelling issues", "prompt": "What causes battery swelling?" },
        { "keyword": "Connector type EV bike", "prompt": "What connector type do bikes use?" },
        { "keyword": "Charging at coffee shops", "prompt": "Can I charge at coffee shops?" },
        { "keyword": "Apartment charging rules", "prompt": "Rules for charging in apartments?" },
        { "keyword": "Fire safety charging", "prompt": "Fire safety tips for charging?" },
        { "keyword": "Range anxiety Vietnam", "prompt": "How to manage range anxiety?" },
        { "keyword": "Trip planning EV", "prompt": "Apps for trip planning with EVs?" },
        { "keyword": "Regen braking range", "prompt": "How much range does regen add?" },
        { "keyword": "Battery cooling system", "prompt": "Do batteries have cooling systems?" },
        { "keyword": "Thermal runaway protection", "prompt": "Protection against thermal runaway?" },
        { "keyword": "Charging status app", "prompt": "App to check charging status?" },
        { "keyword": "VinFast charging station map Hanoi", "prompt": "Hanoi map?" },
        { "keyword": "VinFast charging station map HCMC", "prompt": "HCMC map?" },
        { "keyword": "VinFast charging station map Da Nang", "prompt": "Da Nang map?" },
        { "keyword": "VinFast charging station map Can Tho", "prompt": "Can Tho map?" },
        { "keyword": "Charging station near me", "prompt": "Near me?" },
        { "keyword": "24h charging station", "prompt": "Open 24h?" },
        { "keyword": "Free charging stations", "prompt": "Free charging?" },
        { "keyword": "Charging station shopping mall", "prompt": "In malls?" },
        { "keyword": "Charging station apartment basement", "prompt": "In basements?" },
        { "keyword": "Charging station university", "prompt": "In universities?" },
        { "keyword": "Charging station hospital", "prompt": "In hospitals?" },
        { "keyword": "Portable battery station", "prompt": "Portable stations?" },
        { "keyword": "Battery swap station Hanoi", "prompt": "Swap Hanoi?" },
        { "keyword": "Battery swap station HCMC", "prompt": "Swap HCMC?" },
        { "keyword": "Charging speed VinFast", "prompt": "Speed VinFast?" },
        { "keyword": "Charging speed Dat Bike", "prompt": "Speed Dat Bike?" },
        { "keyword": "Charging speed Yadea", "prompt": "Speed Yadea?" },
        { "keyword": "Battery capacity kWh", "prompt": "Capacity in kWh?" },
        { "keyword": "Battery voltage 72V", "prompt": "72V systems?" },
        { "keyword": "Battery voltage 60V", "prompt": "60V systems?" },
        { "keyword": "Battery voltage 48V", "prompt": "48V systems?" },
        { "keyword": "Ampere hour rating", "prompt": "Ah rating?" },
        { "keyword": "Battery cell manufacturer", "prompt": "Cell maker?" },
        { "keyword": "Samsung SDI battery", "prompt": "Samsung cells?" },
        { "keyword": "LG Chem battery", "prompt": "LG cells?" },
        { "keyword": "CATL battery", "prompt": "CATL cells?" },
        { "keyword": "Gotion High-Tech battery", "prompt": "Gotion cells?" },
        { "keyword": "Battery management system app", "prompt": "BMS app?" },
        { "keyword": "Overcharge protection", "prompt": "Overcharge protect?" },
        { "keyword": "Deep discharge protection", "prompt": "Deep discharge?" },
        { "keyword": "Short circuit protection", "prompt": "Short circuit?" },
        { "keyword": "Battery housing material", "prompt": "Housing material?" }
      ]
    },
    {
      "topic": "Motor and Speed Capabilities",
      "entries": [
        { "keyword": "Motorcycle electric motor specs", "prompt": "What is the peak power output in watts for different electric bike motor configurations?" },
        { "keyword": "Electric two-wheeler models", "prompt": "What is the top speed achievable by various electric scooter models under standard conditions?" },
        { "keyword": "Long-range electric motorbike", "prompt": "Do any electric bikes offer multiple riding modes with distinct acceleration profiles?" },
        { "keyword": "Smart features electric scooter", "prompt": "What is the maximum weight capacity, including rider and cargo, for different electric two-wheelers?" },
        { "keyword": "Commuter electric bike Vietnam", "prompt": "Which electric motorcycle models are designed with a specific incline climbing capability for hills?" },
        { "keyword": "Fastest electric scooter Vietnam", "prompt": "What is currently the fastest street-legal electric motorcycle available in Vietnam?" },
        { "keyword": "High torque electric motor", "prompt": "Which electric bikes have high torque suitable for carrying two people up steep slopes?" },
        { "keyword": "Hub motor vs mid-drive", "prompt": "What are the pros and cons of hub motors versus mid-drive motors for city commuting?" },
        { "keyword": "Dat Bike top speed", "prompt": "Can the Dat Bike Weaver++ reach speeds comparable to a 150cc petrol bike?" },
        { "keyword": "VinFast Theon S acceleration", "prompt": "What is the 0-50 km/h acceleration time for the VinFast Theon S?" },
        { "keyword": "1000W electric scooter", "prompt": "Is a 1000W motor sufficient for climbing bridges in Hanoi with a passenger?" },
        { "keyword": "Electric bike speed limit", "prompt": "Are there software speed limiters on electric bikes that can be unlocked?" },
        { "keyword": "Sport mode electric bike", "prompt": "How significantly does switching to 'Sport Mode' drain the battery?" },
        { "keyword": "Dual motor electric scooter", "prompt": "Are there any dual-motor electric scooters available for better traction?" },
        { "keyword": "Waterproof electric motor", "prompt": "How resistant are electric motors to stalling when driving through deep floods?" },
        { "keyword": "Quiet electric motor", "prompt": "Are there safety concerns regarding how quiet electric motors are for pedestrians?" },
        { "keyword": "Motor overheating issues", "prompt": "Do electric bike motors tend to overheat during heavy traffic jams in summer?" },
        { "keyword": "Brushless DC motor", "prompt": "Why are BLDC motors preferred for modern electric scooters?" },
        { "keyword": "Max load capacity EV", "prompt": "Can electric scooters handle a load of over 150kg without performance loss?" },
        { "keyword": "Regenerative braking efficiency", "prompt": "How much range can be recovered through regenerative braking in city traffic?" },
        { "keyword": "Performance tuning electric bike", "prompt": "Is it legal to modify the controller of an electric bike for higher speed?" },
        { "keyword": "Slope climbing grade", "prompt": "What is the maximum slope grade (in degrees) the bike can climb?" },
        { "keyword": "Motor efficiency percentage", "prompt": "What is the energy efficiency percentage of the motor?" },
        { "keyword": "IP rating electric motor", "prompt": "What is the specific IP rating for dust and water resistance of the motor?" },
        { "keyword": "Controller amperage limit", "prompt": "What is the maximum amperage the controller sends to the motor?" },
        { "keyword": "Motor noise decibels", "prompt": "How many decibels does the motor produce at full speed?" },
        { "keyword": "Direct drive vs gear reduction", "prompt": "Does the motor use direct drive or gear reduction?" },
        { "keyword": "Throttle response sensitivity", "prompt": "Is the throttle response instant or is there a lag?" },
        { "keyword": "Cruise control feature", "prompt": "Does the bike have a cruise control feature for long straight roads?" },
        { "keyword": "Reverse gear electric bike", "prompt": "Does the bike have a reverse mode to help with parking?" },
        { "keyword": "Motor maintenance requirements", "prompt": "Does the electric motor require any periodic maintenance or lubrication?" },
        { "keyword": "Top speed VinFast Vento", "prompt": "Max speed of Vento?" },
        { "keyword": "Dat Bike Weaver++ acceleration", "prompt": "Acceleration of Weaver++?" },
        { "keyword": "Hill climbing power", "prompt": "Can it climb Ba Vi mountain?" },
        { "keyword": "Carrying capacity 2 people", "prompt": "Power with 2 adults?" },
        { "keyword": "Eco mode speed", "prompt": "Speed in Eco mode?" },
        { "keyword": "Motor warranty", "prompt": "Warranty on the motor?" },
        { "keyword": "Hub motor durability", "prompt": "How durable are hub motors?" },
        { "keyword": "Chain drive noise", "prompt": "Is chain drive noisy?" },
        { "keyword": "Belt drive advantages", "prompt": "Advantages of belt drive?" },
        { "keyword": "Water wading depth", "prompt": "Max water depth for motor?" },
        { "keyword": "Speedometer accuracy", "prompt": "Is the speedometer accurate?" },
        { "keyword": "Controller upgrade", "prompt": "Can I upgrade the controller?" },
        { "keyword": "Motor torque specs", "prompt": "Torque in Nm?" },
        { "keyword": "Rated vs Peak power", "prompt": "Difference between rated and peak power?" },
        { "keyword": "Overload protection", "prompt": "Motor overload protection?" },
        { "keyword": "Smooth acceleration", "prompt": "Is acceleration jerky?" },
        { "keyword": "Motor brand", "prompt": "Who manufactures the motor?" },
        { "keyword": "Bosch motor electric bike", "prompt": "Which bikes use Bosch motors?" },
        { "keyword": "Top speed legal limit", "prompt": "Legal speed limit for e-bikes?" },
        { "keyword": "High speed stability", "prompt": "Is it stable at high speeds?" },
        { "keyword": "Motor power 500W", "prompt": "500W performance?" },
        { "keyword": "Motor power 800W", "prompt": "800W performance?" },
        { "keyword": "Motor power 1200W", "prompt": "1200W performance?" },
        { "keyword": "Motor power 1500W", "prompt": "1500W performance?" },
        { "keyword": "Motor power 2000W", "prompt": "2000W performance?" },
        { "keyword": "Motor power 3000W", "prompt": "3000W performance?" },
        { "keyword": "Motor power 5000W", "prompt": "5000W performance?" },
        { "keyword": "Dat Bike Quantum motor power", "prompt": "Quantum motor power?" },
        { "keyword": "VinFast Feliz S motor power", "prompt": "Feliz S motor power?" },
        { "keyword": "VinFast Klara S motor power", "prompt": "Klara S motor power?" },
        { "keyword": "VinFast Vento S motor power", "prompt": "Vento S motor power?" },
        { "keyword": "VinFast Theon S motor power", "prompt": "Theon S motor power?" },
        { "keyword": "Yadea G5 motor power", "prompt": "G5 motor power?" },
        { "keyword": "Pega New Tech motor power", "prompt": "New Tech motor power?" },
        { "keyword": "Top speed 30km/h", "prompt": "Bikes max 30?" },
        { "keyword": "Top speed 50km/h", "prompt": "Bikes max 50?" },
        { "keyword": "Top speed 80km/h", "prompt": "Bikes max 80?" },
        { "keyword": "Top speed 100km/h", "prompt": "Bikes max 100?" },
        { "keyword": "Acceleration 0-30", "prompt": "0-30 times?" },
        { "keyword": "Overtaking power", "prompt": "Passing power?" },
        { "keyword": "Motor cogging torque", "prompt": "Cogging feel?" },
        { "keyword": "Field weakening control", "prompt": "Field weakening?" },
        { "keyword": "Sine wave controller", "prompt": "Sine wave?" },
        { "keyword": "Square wave controller", "prompt": "Square wave?" },
        { "keyword": "FOC controller", "prompt": "FOC control?" },
        { "keyword": "Motor hall sensors", "prompt": "Hall sensors?" },
        { "keyword": "Sensorless motor control", "prompt": "Sensorless?" },
        { "keyword": "Motor winding type", "prompt": "Winding type?" },
        { "keyword": "Copper fill factor", "prompt": "Copper fill?" },
        { "keyword": "Magnet strength grade", "prompt": "Magnet grade?" },
        { "keyword": "Stator lamination", "prompt": "Laminations?" },
        { "keyword": "Motor bearing type", "prompt": "Bearing type?" }
      ]
    },
    {
      "topic": "Maintenance and Service Network",
      "entries": [
        { "keyword": "Electric motorcycle maintenance cost", "prompt": "How many authorized service centers are available for different electric bike manufacturers nationwide?" },
        { "keyword": "EV bike spare parts availability", "prompt": "What is the standard warranty period offered for the battery and motor on various electric scooter models?" },
        { "keyword": "Electric bike warranty comparison", "prompt": "Are replacement parts for different electric bike components readily available in local service shops?" },
        { "keyword": "Durability electric motorcycle Vietnam", "prompt": "What are the typical service intervals recommended for various electric two-wheelers?" },
        { "keyword": "Roadside assistance electric bike", "prompt": "Do any electric bike service plans include roadside assistance coverage in case of breakdowns?" },
        { "keyword": "VinFast service center Hanoi", "prompt": "Where are the official VinFast 3S service centers located in Hanoi?" },
        { "keyword": "Electric scooter tire replacement", "prompt": "Can I replace electric scooter tires at a regular motorbike mechanic shop?" },
        { "keyword": "Brake pad replacement EV", "prompt": "Do electric bikes wear out brake pads faster than petrol bikes due to weight?" },
        { "keyword": "Battery health check", "prompt": "How often should I take my electric bike in for a professional battery health check?" },
        { "keyword": "Yadea warranty policy", "prompt": "What does the Yadea warranty cover regarding water damage to the motor?" },
        { "keyword": "DIY maintenance electric scooter", "prompt": "What basic maintenance tasks can owners perform themselves on electric scooters?" },
        { "keyword": "Spare parts VinFast Feliz", "prompt": "Is there a waiting list for plastic body parts for the VinFast Feliz?" },
        { "keyword": "Mobile repair service EV", "prompt": "Are there mobile mechanics who specialize in fixing electric bikes at home?" },
        { "keyword": "Firmware update electric bike", "prompt": "How do I update the firmware on my smart electric scooter?" },
        { "keyword": "Common faults electric scooters", "prompt": "What are the most reported technical faults for Pega electric bikes?" },
        { "keyword": "Washing electric bike safety", "prompt": "What precautions should be taken when pressure washing an electric motorbike?" },
        { "keyword": "Lubrication electric bike chain", "prompt": "Do belt-drive electric bikes require less maintenance than chain-drive ones?" },
        { "keyword": "Controller repair cost", "prompt": "How expensive is it to replace a fried controller unit on an electric scooter?" },
        { "keyword": "Headlight replacement EV", "prompt": "Are LED headlight units for electric bikes standard or proprietary?" },
        { "keyword": "Genuine parts vs fake", "prompt": "How can I distinguish between genuine and counterfeit electric bike batteries?" },
        { "keyword": "Authorized dealer service", "prompt": "Is the warranty void if I service my electric bike at an unauthorized shop?" },
        { "keyword": "Tire pressure monitoring", "prompt": "Can I install aftermarket TPMS on my electric scooter?" },
        { "keyword": "Fork oil change interval", "prompt": "How often does the front fork oil need changing on electric bikes?" },
        { "keyword": "Belt tension adjustment", "prompt": "How do I adjust the belt tension on a Dat Bike Weaver?" },
        { "keyword": "Bearing replacement cost", "prompt": "How much does it cost to replace wheel bearings on a Yadea scooter?" },
        { "keyword": "Service app booking", "prompt": "Can I book a service appointment via the manufacturer's app?" },
        { "keyword": "Error code guide", "prompt": "Where can I find a guide to deciphering error codes on the dashboard?" },
        { "keyword": "Rust protection", "prompt": "What products should I use to protect the frame from rust?" },
        { "keyword": "Throttle cable maintenance", "prompt": "Do electronic throttles require any maintenance?" },
        { "keyword": "Coolant check EV", "prompt": "Do any high-performance electric bikes use liquid cooling that needs checking?" },
        { "keyword": "Post-flood maintenance", "prompt": "What should I do immediately after riding through a flood?" },
        { "keyword": "Regular service cost", "prompt": "Cost of regular service?" },
        { "keyword": "VinFast 3S locations", "prompt": "Locations of 3S centers?" },
        { "keyword": "Yadea service quality", "prompt": "Quality of Yadea service?" },
        { "keyword": "Dat Bike care package", "prompt": "Dat Bike care packages?" },
        { "keyword": "Tire puncture repair", "prompt": "Repairing punctures on EVs?" },
        { "keyword": "Brake fluid change", "prompt": "When to change brake fluid?" },
        { "keyword": "Software glitch fix", "prompt": "Fixing software glitches?" },
        { "keyword": "Battery connector cleaning", "prompt": "Cleaning battery connectors?" },
        { "keyword": "Motor magnet check", "prompt": "Checking motor magnets?" },
        { "keyword": "Suspension seal replacement", "prompt": "Replacing suspension seals?" },
        { "keyword": "Plastic fairing repair", "prompt": "Repairing cracked plastics?" },
        { "keyword": "Kickstand repair", "prompt": "Fixing loose kickstand?" },
        { "keyword": "Horn replacement", "prompt": "Replacing the horn?" },
        { "keyword": "Mirror tightening", "prompt": "Tightening loose mirrors?" },
        { "keyword": "Service manual download", "prompt": "Downloading service manuals?" },
        { "keyword": "Mechanic training EV", "prompt": "Are mechanics trained for EVs?" },
        { "keyword": "24/7 rescue service", "prompt": "Is there 24/7 rescue?" },
        { "keyword": "Warranty claim process", "prompt": "How to claim warranty?" },
        { "keyword": "Scheduled maintenance app", "prompt": "App reminders for service?" },
        { "keyword": "Chain lube type", "prompt": "Best chain lube for EVs?" },
        { "keyword": "VinFast 3S District 1", "prompt": "3S District 1?" },
        { "keyword": "VinFast 3S District 7", "prompt": "3S District 7?" },
        { "keyword": "VinFast 3S Thu Duc", "prompt": "3S Thu Duc?" },
        { "keyword": "VinFast 3S Cau Giay", "prompt": "3S Cau Giay?" },
        { "keyword": "VinFast 3S Long Bien", "prompt": "3S Long Bien?" },
        { "keyword": "Yadea service Hanoi", "prompt": "Yadea service Hanoi?" },
        { "keyword": "Yadea service HCMC", "prompt": "Yadea service HCMC?" },
        { "keyword": "Dat Bike garage", "prompt": "Dat Bike garage?" },
        { "keyword": "Pega service center", "prompt": "Pega service?" },
        { "keyword": "Battery recycling center", "prompt": "Recycling center?" },
        { "keyword": "Tire shop EV", "prompt": "EV tire shop?" },
        { "keyword": "Car wash for EV", "prompt": "Car wash for EV?" },
        { "keyword": "Detailing shop EV", "prompt": "Detailing for EV?" },
        { "keyword": "Seat upholstery repair", "prompt": "Seat repair?" },
        { "keyword": "Locksmith for EV key", "prompt": "Locksmith for key?" },
        { "keyword": "Towing service EV", "prompt": "Towing for EV?" },
        { "keyword": "Insurance claim support", "prompt": "Insurance support?" },
        { "keyword": "Customer support email", "prompt": "Support email?" },
        { "keyword": "Complaint hotline", "prompt": "Complaint hotline?" },
        { "keyword": "Technical support chat", "prompt": "Tech support chat?" },
        { "keyword": "User manual Vietnamese", "prompt": "Manual in Vietnamese?" },
        { "keyword": "Community forum support", "prompt": "Forum support?" },
        { "keyword": "Facebook group mechanics", "prompt": "Mechanic groups?" },
        { "keyword": "YouTube repair tutorials", "prompt": "Repair tutorials?" },
        { "keyword": "Spare parts catalog", "prompt": "Parts catalog?" },
        { "keyword": "Oil seal leak", "prompt": "Oil seal leak?" },
        { "keyword": "Steering stem bearing", "prompt": "Steering bearing?" },
        { "keyword": "Swingarm bushing", "prompt": "Swingarm bushing?" },
        { "keyword": "Shock absorber leak", "prompt": "Shock leak?" },
        { "keyword": "Display screen crack", "prompt": "Screen crack?" },
        { "keyword": "Switch contact cleaner", "prompt": "Switch cleaner?" }
      ]
    },
    {
      "topic": "Legal Requirements and Documentation",
      "entries": [
        { "keyword": "EV bike registration Vietnam", "prompt": "Which electric bike models require a specific driver's license category for operation?" },
        { "keyword": "Government incentives EV Vietnam", "prompt": "What documentation is typically needed to register different electric two-wheelers in local provinces?" },
        { "keyword": "Electric scooter road tax", "prompt": "Are there specific electric scooter models that are exempt from certain road taxes or fees?" },
        { "keyword": "Helmet laws electric bike", "prompt": "What are the legal requirements regarding helmet usage for riders of various electric motorcycles?" },
        { "keyword": "License plate electric bike", "prompt": "Do any electric bikes qualify for specific licensing plate categories based on their motor power?" },
        { "keyword": "Driver license A1 for EV", "prompt": "Do I need an A1 license to drive a VinFast Feliz S?" },
        { "keyword": "No license electric scooter", "prompt": "What are the best electric scooter models for high school students without a license?" },
        { "keyword": "Age limit riding electric bike", "prompt": "What is the minimum legal age to operate an electric bicycle in Vietnam?" },
        { "keyword": "Mandatory insurance electric bike", "prompt": "Is civil liability insurance mandatory for electric motorbikes?" },
        { "keyword": "Blue card registration", "prompt": "How long does it take to get the blue registration card for a new EV bike?" },
        { "keyword": "Transfer ownership electric bike", "prompt": "What is the procedure for transferring ownership of a used electric motorcycle?" },
        { "keyword": "Fine for no helmet EV", "prompt": "Are the fines for traffic violations on electric bikes the same as petrol bikes?" },
        { "keyword": "Electric bicycle vs motorcycle", "prompt": "What is the legal distinction between an electric bicycle and an electric motorcycle?" },
        { "keyword": "Traffic laws electric bike", "prompt": "Are electric bikes allowed on elevated ring roads in Hanoi?" },
        { "keyword": "Imported electric bike tax", "prompt": "What taxes apply when importing a custom electric bike into Vietnam?" },
        { "keyword": "Modifying electric bike legal", "prompt": "Is it legal to modify the frame or lights of an electric scooter?" },
        { "keyword": "Passenger rules electric bike", "prompt": "Is it legal to carry three people on an electric scooter?" },
        { "keyword": "Student riding rules", "prompt": "Can students ride electric bikes to school legally?" },
        { "keyword": "Lost registration card EV", "prompt": "What should I do if I lose the registration papers for my electric bike?" },
        { "keyword": "VinFast Impes legal age", "prompt": "Is the VinFast Impes legal for 15-year-old students?" },
        { "keyword": "Installment papers requirements", "prompt": "What documents are required to buy an electric bike on installment?" },
        { "keyword": "International driving permit EV", "prompt": "Can I use an International Driving Permit to rent an electric bike in Vietnam?" },
        { "keyword": "Parking fines electric bike", "prompt": "Are parking fines the same for electric and petrol bikes?" },
        { "keyword": "Helmet certification standard", "prompt": "Does my helmet need a specific safety stamp to be legal?" },
        { "keyword": "Carrying goods legal limit", "prompt": "What are the legal dimensions for cargo carried on a motorbike?" },
        { "keyword": "Driving under influence EV", "prompt": "Do DUI laws apply to electric bicycles?" },
        { "keyword": "License plate visibility", "prompt": "Is it illegal to obscure the license plate with a bike rack?" },
        { "keyword": "Horn usage laws", "prompt": "Are there laws regarding the use of horns in hospital zones?" },
        { "keyword": "Headlight requirements day", "prompt": "Is it mandatory to keep headlights on during the day?" },
        { "keyword": "Lane discipline electric bike", "prompt": "Which lane must electric bikes use on multi-lane roads?" },
        { "keyword": "Safety inspection certificate", "prompt": "Do electric bikes require a periodic safety inspection certificate?" },
        { "keyword": "Registration cost Hanoi", "prompt": "Cost to register in Hanoi?" },
        { "keyword": "Registration cost HCMC", "prompt": "Cost to register in HCMC?" },
        { "keyword": "License plate color EV", "prompt": "Is the plate color different?" },
        { "keyword": "Documents for license plate", "prompt": "Papers needed for plate?" },
        { "keyword": "Temporary license plate", "prompt": "How to get temporary plates?" },
        { "keyword": "Buying bike for child", "prompt": "Legal aspects of buying for child?" },
        { "keyword": "Ownership transfer fee", "prompt": "Fee for ownership transfer?" },
        { "keyword": "Notary public bike sale", "prompt": "Do I need a notary for sale?" },
        { "keyword": "Insurance cost per year", "prompt": "Yearly insurance cost?" },
        { "keyword": "Electric bike classification", "prompt": "Classes of e-bikes?" },
        { "keyword": "Under 50cc equivalent", "prompt": "Equivalent to 50cc rules?" },
        { "keyword": "Driving on highway", "prompt": "Can I drive on highways?" },
        { "keyword": "Sidewalk parking laws", "prompt": "Is sidewalk parking legal?" },
        { "keyword": "Impounded electric bike", "prompt": "Retrieving impounded bike?" },
        { "keyword": "Red invoice electric bike", "prompt": "Importance of red invoice?" },
        { "keyword": "Chassis number location", "prompt": "Where is the chassis number?" },
        { "keyword": "Engine number location", "prompt": "Where is the engine number?" },
        { "keyword": "Traffic police checks", "prompt": "Do police check EVs often?" },
        { "keyword": "Helmet fine amount", "prompt": "Amount of helmet fine?" },
        { "keyword": "Speeding fine EV", "prompt": "Speeding fines for EVs?" },
        { "keyword": "Registration District 1", "prompt": "Register in D1?" },
        { "keyword": "Registration District 3", "prompt": "Register in D3?" },
        { "keyword": "Registration Thu Duc", "prompt": "Register in Thu Duc?" },
        { "keyword": "Registration Tan Binh", "prompt": "Register in Tan Binh?" },
        { "keyword": "Registration Ba Dinh", "prompt": "Register in Ba Dinh?" },
        { "keyword": "Registration Cau Giay", "prompt": "Register in Cau Giay?" },
        { "keyword": "Non-resident registration", "prompt": "Register without residency?" },
        { "keyword": "Online registration portal", "prompt": "Register online?" },
        { "keyword": "Appointment for registration", "prompt": "Appointment needed?" },
        { "keyword": "Plate number selection", "prompt": "Choose number?" },
        { "keyword": "Lucky plate number", "prompt": "Lucky number?" },
        { "keyword": "Auction plate number", "prompt": "Auction number?" },
        { "keyword": "Lost license plate", "prompt": "Lost plate?" },
        { "keyword": "Damaged license plate", "prompt": "Damaged plate?" },
        { "keyword": "Address change registration", "prompt": "Change address?" },
        { "keyword": "Color change registration", "prompt": "Change color?" },
        { "keyword": "Engine change registration", "prompt": "Change motor?" },
        { "keyword": "Frame change registration", "prompt": "Change frame?" },
        { "keyword": "Scrapping deregistration", "prompt": "Deregister scrap?" },
        { "keyword": "Power of attorney sale", "prompt": "POA sale?" },
        { "keyword": "Inheritance transfer", "prompt": "Inheritance?" },
        { "keyword": "Gift transfer", "prompt": "Gifting bike?" },
        { "keyword": "Company car registration", "prompt": "Company bike?" },
        { "keyword": "Rental business registration", "prompt": "Rental biz?" },
        { "keyword": "Transport business license", "prompt": "Transport license?" },
        { "keyword": "A1 license cost", "prompt": "A1 cost?" },
        { "keyword": "A1 license exam", "prompt": "A1 exam?" },
        { "keyword": "A1 license practice", "prompt": "A1 practice?" },
        { "keyword": "Driving school EV", "prompt": "Learn on EV?" },
        { "keyword": "License renewal", "prompt": "Renew license?" },
        { "keyword": "Lost license replacement", "prompt": "Replace license?" }
      ]
    },
    {
      "topic": "Safety Features and Design",
      "entries": [
        { "keyword": "Safety features EV bikes", "prompt": "Which electric bike models incorporate an anti-lock braking system (ABS) or combined braking system (CBS)?" },
        { "keyword": "Smart features electric scooter", "prompt": "Do any electric scooters come equipped with built-in GPS tracking or anti-theft alarms as standard?" },
        { "keyword": "Durability electric motorcycle Vietnam", "prompt": "What type of lighting system (e.g., LED, halogen) is standard on various electric motorcycle models for visibility?" },
        { "keyword": "Rider visibility electric bike", "prompt": "Are there specific electric bikes designed with features for improved rider visibility in heavy traffic?" },
        { "keyword": "Frame construction materials", "prompt": "What materials are primarily used in the frame construction of different electric two-wheelers for crash safety?" },
        { "keyword": "ABS electric scooter Vietnam", "prompt": "Is ABS standard on premium electric scooters like the VinFast Vento?" },
        { "keyword": "Disc brakes vs drum brakes", "prompt": "Do budget electric scooters use disc brakes or drum brakes?" },
        { "keyword": "Smart key electric motorcycle", "prompt": "How secure are the smart key systems on modern electric motorbikes?" },
        { "keyword": "Anti-theft alarm electric scooter", "prompt": "How sensitive are the anti-theft alarms on Yadea scooters?" },
        { "keyword": "GPS tracker electric bike", "prompt": "Can I track my stolen electric bike using the manufacturer's app?" },
        { "keyword": "Waterproof rating IP67", "prompt": "Which electric bike models have the highest IP rating for flood resistance?" },
        { "keyword": "LED headlight brightness", "prompt": "Are the stock LED headlights on electric bikes bright enough for rural roads?" },
        { "keyword": "Suspension quality Vietnam", "prompt": "Which electric scooters have the best suspension for potholes?" },
        { "keyword": "Tire grip wet road", "prompt": "Do stock tires on electric bikes perform well during the rainy season?" },
        { "keyword": "Horn loudness electric scooter", "prompt": "Is the horn on electric bikes loud enough for chaotic city traffic?" },
        { "keyword": "Emergency braking distance", "prompt": "How does the braking distance of an EV bike compare to a petrol bike?" },
        { "keyword": "Stability control electric bike", "prompt": "Do any electric motorcycles feature traction control systems?" },
        { "keyword": "Child lock electric scooter", "prompt": "Is there a safety switch to prevent children from accidentally accelerating?" },
        { "keyword": "Side stand sensor", "prompt": "Does the motor cut off automatically when the side stand is down?" },
        { "keyword": "Battery fire safety", "prompt": "What safety mechanisms prevent battery fires in VinFast scooters?" },
        { "keyword": "Fireproof battery case", "prompt": "Are the battery packs encased in fire-retardant materials?" },
        { "keyword": "Turn signal visibility", "prompt": "Are the turn signals on electric bikes clearly visible in daylight?" },
        { "keyword": "Reflective stickers safety", "prompt": "Do manufacturers apply reflective strips for night safety?" },
        { "keyword": "Center stand stability", "prompt": "Is the center stand easy to deploy on heavier electric bikes?" },
        { "keyword": "Crash test electric scooter", "prompt": "Are there any crash test ratings available for electric motorcycles?" },
        { "keyword": "Tire brand stock", "prompt": "What brand of tires comes stock on the VinFast Theon?" },
        { "keyword": "Tubeless tires", "prompt": "Are tubeless tires standard on all new electric scooters?" },
        { "keyword": "Frame rigidity", "prompt": "Is the frame rigid enough for high-speed cornering?" },
        { "keyword": "Mirror visibility", "prompt": "Do the stock mirrors provide a wide field of view?" },
        { "keyword": "Handlebar vibration", "prompt": "Does the handlebar vibrate excessively at top speed?" },
        { "keyword": "Brake lever adjustability", "prompt": "Are the brake levers adjustable for different hand sizes?" },
        { "keyword": "Throttle sticking safety", "prompt": "Are there fail-safes if the electronic throttle sticks?" },
        { "keyword": "Lighting certification", "prompt": "Do the lights meet international safety standards?" },
        { "keyword": "Pillion handle grip", "prompt": "Are the grab rails for the passenger secure?" },
        { "keyword": "Emergency hazard lights", "prompt": "Does the bike have a hazard light switch for emergencies?" },
        { "keyword": "Remote lock unlock", "prompt": "Can I lock/unlock remotely?" },
        { "keyword": "Find my bike feature", "prompt": "How does find my bike work?" },
        { "keyword": "Automatic headlight", "prompt": "Do headlights turn on automatically?" },
        { "keyword": "Cornering lights", "prompt": "Are there cornering lights?" },
        { "keyword": "Brake light brightness", "prompt": "Is the brake light bright enough?" },
        { "keyword": "Traction control EV", "prompt": "Is traction control needed?" },
        { "keyword": "Wheel size safety", "prompt": "Larger wheels for safety?" },
        { "keyword": "Ground clearance safety", "prompt": "Is high ground clearance safer?" },
        { "keyword": "Dual disc brakes", "prompt": "Benefits of dual disc brakes?" },
        { "keyword": "Regen braking safety", "prompt": "Does regen affect stability?" },
        { "keyword": "Battery lock security", "prompt": "Is the battery lock secure?" },
        { "keyword": "Seat lock security", "prompt": "Is the seat lock tamper proof?" },
        { "keyword": "Steering lock", "prompt": "How strong is the steering lock?" },
        { "keyword": "App notification theft", "prompt": "Notifications for theft attempts?" },
        { "keyword": "Fall detection sensor", "prompt": "Is there a fall sensor?" },
        { "keyword": "Waterproof IP68", "prompt": "IP68 available?" },
        { "keyword": "Dustproof IP65", "prompt": "IP65 available?" },
        { "keyword": "Wading depth 300mm", "prompt": "300mm wading?" },
        { "keyword": "Wading depth 500mm", "prompt": "500mm wading?" },
        { "keyword": "Chassis weld quality", "prompt": "Weld quality?" },
        { "keyword": "Fork diameter", "prompt": "Fork size?" },
        { "keyword": "Rear shock type", "prompt": "Shock type?" },
        { "keyword": "Mono shock vs dual shock", "prompt": "Mono vs dual?" },
        { "keyword": "Tire size 10 inch", "prompt": "10 inch tires?" },
        { "keyword": "Tire size 12 inch", "prompt": "12 inch tires?" },
        { "keyword": "Tire size 14 inch", "prompt": "14 inch tires?" },
        { "keyword": "Tire size 16 inch", "prompt": "16 inch tires?" },
        { "keyword": "Michelin City Grip EV", "prompt": "Michelin tires?" },
        { "keyword": "Pirelli Angel Scooter", "prompt": "Pirelli tires?" },
        { "keyword": "Cheng Shin tires", "prompt": "Cheng Shin tires?" },
        { "keyword": "Kenda tires", "prompt": "Kenda tires?" },
        { "keyword": "Maxxis tires", "prompt": "Maxxis tires?" },
        { "keyword": "Ceramic brake pads", "prompt": "Ceramic pads?" },
        { "keyword": "Sintered brake pads", "prompt": "Sintered pads?" },
        { "keyword": "Brake fluid DOT4", "prompt": "DOT4 fluid?" },
        { "keyword": "Steel braided brake lines", "prompt": "Braided lines?" },
        { "keyword": "Handlebar weights", "prompt": "Bar weights?" },
        { "keyword": "Windshield safety", "prompt": "Windshield safety?" },
        { "keyword": "Leg shield protection", "prompt": "Leg shield?" },
        { "keyword": "Battery BMS safety", "prompt": "BMS safety?" },
        { "keyword": "Short circuit fuse", "prompt": "Fuses?" },
        { "keyword": "Circuit breaker", "prompt": "Breaker?" },
        { "keyword": "Kill switch", "prompt": "Kill switch?" },
        { "keyword": "Tilt sensor", "prompt": "Tilt sensor?" }
      ]
    },
    {
      "topic": "Availability and Dealerships",
      "entries": [
        { "keyword": "Purchase locations electric scooter Vietnam", "prompt": "How many dedicated showrooms are there for various electric bike manufacturers in key urban centers?" },
        { "keyword": "Electric two-wheeler models", "prompt": "Which electric scooter models can be test-ridden at multiple dealership locations?" },
        { "keyword": "Buy electric motorcycle online", "prompt": "Are specific electric motorcycle models available for purchase through online platforms?" },
        { "keyword": "Delivery waiting period EV", "prompt": "What is the typical waiting period for delivery after ordering different electric two-wheelers?" },
        { "keyword": "DTC sales electric bike", "prompt": "Do any electric bike manufacturers offer direct-to-consumer sales or a subscription model for their vehicles?" },
        { "keyword": "VinFast showroom Da Nang", "prompt": "Where can I test drive VinFast scooters in Da Nang?" },
        { "keyword": "Dat Bike store Ho Chi Minh", "prompt": "Does Dat Bike have a physical experience center in District 2?" },
        { "keyword": "Yadea dealership Hanoi", "prompt": "Find the nearest authorized Yadea dealer in Cau Giay district." },
        { "keyword": "Pega electric bike shop", "prompt": "Are Pega bikes available in multi-brand electric vehicle shops?" },
        { "keyword": "Used electric bike market", "prompt": "Which websites are best for finding used electric scooters?" },
        { "keyword": "Test ride electric scooter", "prompt": "Do I need to book an appointment to test ride a Selex scooter?" },
        { "keyword": "Pre-order new electric bike", "prompt": "What are the benefits of pre-ordering the latest electric bike model?" },
        { "keyword": "Electric bike rural availability", "prompt": "Are electric bike dealerships common in rural provinces?" },
        { "keyword": "Genuine dealer vs reseller", "prompt": "How to identify a genuine authorized dealer versus a reseller?" },
        { "keyword": "Showroom opening hours", "prompt": "Are electric bike showrooms open on Sundays?" },
        { "keyword": "Customer service hotline", "prompt": "Is there a 24/7 hotline for electric bike support?" },
        { "keyword": "Facebook groups buying EV bike", "prompt": "Which Facebook groups are active for buying and selling EV bikes?" },
        { "keyword": "Cho Tot electric scooter", "prompt": "Is it safe to buy electric scooters on Cho Tot?" },
        { "keyword": "Tiki electric motorbike", "prompt": "Does Tiki offer home delivery for electric motorcycles?" },
        { "keyword": "Shopee electric scooter parts", "prompt": "Can I find genuine spare parts on Shopee?" },
        { "keyword": "Import electric bike service", "prompt": "Are there services that import electric bikes from China on demand?" },
        { "keyword": "Exclusive distributor Vietnam", "prompt": "Who is the exclusive distributor for NIU scooters in Vietnam?" },
        { "keyword": "Flagship store VinFast", "prompt": "Where is the largest VinFast flagship store located?" },
        { "keyword": "Test drive booking app", "prompt": "Can I book a test drive through a mobile app?" },
        { "keyword": "Availability of colors", "prompt": "Are all color options usually available in stock at dealerships?" },
        { "keyword": "Pop-up store locations", "prompt": "Are there any pop-up stores in shopping malls to see the bikes?" },
        { "keyword": "Inventory status check", "prompt": "Can I check the stock inventory of a dealer online?" },
        { "keyword": "Referral program EV", "prompt": "Is there a referral program for bringing new customers to VinFast?" },
        { "keyword": "Corporate fleet sales", "prompt": "Who do I contact for bulk corporate fleet purchases?" },
        { "keyword": "Test ride requirements", "prompt": "What documents do I need to bring for a test ride?" },
        { "keyword": "Delivery cost to home", "prompt": "Is home delivery free for new electric bikes?" },
        { "keyword": "Dealer network map", "prompt": "Is there an interactive map of the entire dealer network?" },
        { "keyword": "Service center colocation", "prompt": "Are dealerships always co-located with service centers?" },
        { "keyword": "Certified pre-owned program", "prompt": "Does the manufacturer offer a certified pre-owned program?" },
        { "keyword": "Exporting electric bike", "prompt": "Can I buy a bike in Vietnam and export it to another country?" },
        { "keyword": "VinFast dealer District 1", "prompt": "Dealer in District 1?" },
        { "keyword": "Yadea dealer Hai Phong", "prompt": "Dealer in Hai Phong?" },
        { "keyword": "Dat Bike dealer Hanoi", "prompt": "Dealer in Hanoi?" },
        { "keyword": "Electric bike shop Hue", "prompt": "Shop in Hue?" },
        { "keyword": "Buy EV Can Tho", "prompt": "Buying in Can Tho?" },
        { "keyword": "Online configuration tool", "prompt": "Is there an online configurator?" },
        { "keyword": "Deposit refund policy", "prompt": "Is the deposit refundable?" },
        { "keyword": "Installment partner banks", "prompt": "Which banks partner for installments?" },
        { "keyword": "Trade-in valuation", "prompt": "How is trade-in value calculated?" },
        { "keyword": "Stock availability Feliz S", "prompt": "Is Feliz S in stock?" },
        { "keyword": "Stock availability Vento", "prompt": "Is Vento in stock?" },
        { "keyword": "Launch event invitation", "prompt": "How to get invited to launches?" },
        { "keyword": "Newsletter subscription", "prompt": "Subscribe to newsletter?" },
        { "keyword": "Social media channels", "prompt": "Official social media?" },
        { "keyword": "Dealer rating reviews", "prompt": "Where to find dealer reviews?" },
        { "keyword": "VinFast showroom Times City", "prompt": "Times City showroom?" },
        { "keyword": "VinFast showroom Royal City", "prompt": "Royal City showroom?" },
        { "keyword": "VinFast showroom Landmark 81", "prompt": "Landmark 81 showroom?" },
        { "keyword": "Yadea Xmen for sale", "prompt": "Xmen for sale?" },
        { "keyword": "Yadea G5 stock", "prompt": "G5 stock?" },
        { "keyword": "Dat Bike Weaver 200 stock", "prompt": "Weaver 200 stock?" },
        { "keyword": "Buy EV Lazada", "prompt": "Buy on Lazada?" },
        { "keyword": "Buy EV TikTok Shop", "prompt": "Buy on TikTok?" },
        { "keyword": "Facebook Marketplace EV", "prompt": "FB Marketplace?" },
        { "keyword": "Authorized reseller list", "prompt": "Reseller list?" },
        { "keyword": "Grey market EV", "prompt": "Grey market?" },
        { "keyword": "Parallel import EV", "prompt": "Parallel import?" },
        { "keyword": "Chinese EV import", "prompt": "Chinese import?" },
        { "keyword": "Japanese EV import", "prompt": "Japanese import?" },
        { "keyword": "Dealer commission", "prompt": "Dealer commission?" },
        { "keyword": "Sales agent contact", "prompt": "Agent contact?" },
        { "keyword": "Brochure download", "prompt": "Download brochure?" },
        { "keyword": "Price quote request", "prompt": "Request quote?" },
        { "keyword": "Test ride at home", "prompt": "Test ride home?" },
        { "keyword": "Virtual showroom tour", "prompt": "Virtual tour?" },
        { "keyword": "Dealer events", "prompt": "Dealer events?" },
        { "keyword": "Weekend sales event", "prompt": "Weekend sales?" },
        { "keyword": "Roadshow location", "prompt": "Roadshow?" },
        { "keyword": "Dealer fraud alert", "prompt": "Fraud alert?" },
        { "keyword": "Scam warning EV", "prompt": "Scam warning?" },
        { "keyword": "Trusted seller list", "prompt": "Trusted sellers?" },
        { "keyword": "Buyer protection", "prompt": "Buyer protection?" },
        { "keyword": "Warranty registration", "prompt": "Register warranty?" },
        { "keyword": "Extended warranty purchase", "prompt": "Buy warranty?" },
        { "keyword": "Accessories shop", "prompt": "Accessories?" },
        { "keyword": "Helmet shop", "prompt": "Helmets?" }
      ]
    },
    {
      "topic": "Ride Comfort and Aesthetics",
      "entries": [
        { "keyword": "Electric two-wheeler models", "prompt": "Which electric bike models offer adjustable suspension systems for varying road conditions?" },
        { "keyword": "Smart features electric scooter", "prompt": "What seat height options are available for different electric scooter models to accommodate riders?" },
        { "keyword": "Digital dashboard display", "prompt": "Do any electric motorcycles feature a digital display dashboard with customizable information?" },
        { "keyword": "Under-seat storage capacity", "prompt": "What storage capacity, such as under-seat space or built-in compartments, is available on various electric two-wheelers?" },
        { "keyword": "Customizable aesthetics", "prompt": "Which electric bike models come with a variety of factory color options or aesthetic customization packages?" },
        { "keyword": "Comfortable seat electric scooter", "prompt": "Which electric scooter has the most comfortable seat for long commutes?" },
        { "keyword": "Seat height for short riders", "prompt": "What are the best electric scooters for riders under 1m60?" },
        { "keyword": "Legroom electric bike", "prompt": "Does the VinFast Feliz offer enough legroom for tall drivers?" },
        { "keyword": "Suspension softness", "prompt": "Is the suspension on the Dat Bike Weaver too stiff for city riding?" },
        { "keyword": "Handlebar height adjustment", "prompt": "Can the handlebars be adjusted on Pega electric bikes?" },
        { "keyword": "Stylish electric scooter women", "prompt": "What are the most fashionable electric scooters marketed towards women?" },
        { "keyword": "Sporty design electric bike", "prompt": "Are there any electric bikes with a naked sportbike look?" },
        { "keyword": "Retro style electric scooter", "prompt": "Are there electric scooters that look like classic Vespas?" },
        { "keyword": "Custom paint electric bike", "prompt": "Does VinFast offer custom paint jobs for their scooters?" },
        { "keyword": "Matte black electric scooter", "prompt": "Which models are available in a matte black finish?" },
        { "keyword": "Color options VinFast Feliz", "prompt": "How many color variations are available for the Feliz S?" },
        { "keyword": "Hook for shopping bags", "prompt": "Is there a convenient hook for hanging shopping bags?" },
        { "keyword": "Footrest comfort passenger", "prompt": "Are the rear footrests comfortable for passengers on long rides?" },
        { "keyword": "Vibration electric bike", "prompt": "Do electric bikes vibrate less than petrol bikes at high speeds?" },
        { "keyword": "Noise level riding", "prompt": "How quiet is the ride on a premium electric scooter?" },
        { "keyword": "Wind protection electric scooter", "prompt": "Do windshield accessories help with wind noise?" },
        { "keyword": "Ergonomics for long ride", "prompt": "Is the riding posture on the Theon S suitable for touring?" },
        { "keyword": "Seat material quality", "prompt": "Does the seat leather degrade quickly in the Vietnam sun?" },
        { "keyword": "Light weight electric bike", "prompt": "What is the lightest electric scooter easy to maneuver for beginners?" },
        { "keyword": "LED strip lights aesthetics", "prompt": "Do the positioning lights give the bike a modern aesthetic?" },
        { "keyword": "Pillion seat width", "prompt": "Is the passenger seat wide enough for comfort?" },
        { "keyword": "Dashboard glare sun", "prompt": "Is the digital dashboard readable in direct sunlight?" },
        { "keyword": "App connectivity interface", "prompt": "Is the mobile app interface user-friendly and aesthetically pleasing?" },
        { "keyword": "Glove box storage", "prompt": "Is there a front glove box for storing a phone or wallet?" },
        { "keyword": "USB charging port location", "prompt": "Is the USB port conveniently located for charging a phone while riding?" },
        { "keyword": "Mirror aesthetics", "prompt": "Do the mirrors match the overall style of the bike?" },
        { "keyword": "Decal kits customization", "prompt": "Are there official decal kits to personalize the bike?" },
        { "keyword": "Key fob design", "prompt": "Is the smart key fob compact and stylish?" },
        { "keyword": "Grip comfort", "prompt": "Are the handlebar grips comfortable without gloves?" },
        { "keyword": "Turn signal sound", "prompt": "Is the turn signal clicking sound pleasant or annoying?" },
        { "keyword": "Fender design rain", "prompt": "Do the fenders protect well against splashes?" },
        { "keyword": "Switchgear quality", "prompt": "Do the buttons feel premium?" },
        { "keyword": "Floorboard width", "prompt": "Is the floorboard wide enough?" },
        { "keyword": "Center of gravity", "prompt": "Is the center of gravity low for stability?" },
        { "keyword": "Standover height", "prompt": "Is the standover height manageable?" },
        { "keyword": "Color fading sun", "prompt": "Does the paint fade in the sun?" },
        { "keyword": "Rim design aesthetics", "prompt": "Do the rims look sporty?" },
        { "keyword": "License plate holder style", "prompt": "Is the plate holder stylish?" },
        { "keyword": "Dashboard themes", "prompt": "Can I change dashboard themes?" },
        { "keyword": "Welcome lights", "prompt": "Are there welcome lights?" },
        { "keyword": "Seat latch mechanism", "prompt": "Is the seat latch easy to use?" },
        { "keyword": "Helmet hook security", "prompt": "Is the helmet hook secure?" },
        { "keyword": "Phone mount compatibility", "prompt": "Can I attach a phone mount?" },
        { "keyword": "Cup holder", "prompt": "Is there a cup holder?" },
        { "keyword": "Rain coat storage", "prompt": "Space for a rain coat?" },
        { "keyword": "Matte green VinFast", "prompt": "Matte green available?" },
        { "keyword": "Glossy white Yadea", "prompt": "Glossy white available?" },
        { "keyword": "Red Dat Bike Weaver", "prompt": "Red Weaver?" },
        { "keyword": "Blue Pega", "prompt": "Blue Pega?" },
        { "keyword": "Yellow electric scooter", "prompt": "Yellow scooter?" },
        { "keyword": "Pink electric scooter", "prompt": "Pink scooter?" },
        { "keyword": "Cute electric scooter", "prompt": "Cute scooter?" },
        { "keyword": "Aggressive design EV", "prompt": "Aggressive design?" },
        { "keyword": "Futuristic design EV", "prompt": "Futuristic design?" },
        { "keyword": "Classic design EV", "prompt": "Classic design?" },
        { "keyword": "Cafe racer EV", "prompt": "Cafe racer style?" },
        { "keyword": "Scrambler EV", "prompt": "Scrambler style?" },
        { "keyword": "Minibike EV", "prompt": "Minibike style?" },
        { "keyword": "Maxi scooter EV", "prompt": "Maxi scooter style?" },
        { "keyword": "Step-through frame", "prompt": "Step-through?" },
        { "keyword": "Underbone frame", "prompt": "Underbone?" },
        { "keyword": "Seat upholstery custom", "prompt": "Custom seat?" },
        { "keyword": "Carbon fiber parts", "prompt": "Carbon parts?" },
        { "keyword": "Windshield tint", "prompt": "Tinted windshield?" },
        { "keyword": "Top box compatibility", "prompt": "Top box?" },
        { "keyword": "Pannier rack", "prompt": "Panniers?" },
        { "keyword": "Saddle bags", "prompt": "Saddle bags?" },
        { "keyword": "Backrest for passenger", "prompt": "Passenger backrest?" },
        { "keyword": "Heated grips", "prompt": "Heated grips?" },
        { "keyword": "Heated seat", "prompt": "Heated seat?" },
        { "keyword": "Ventilated seat", "prompt": "Ventilated seat?" },
        { "keyword": "Bluetooth speaker", "prompt": "Bluetooth speaker?" },
        { "keyword": "Music player control", "prompt": "Music control?" },
        { "keyword": "Navigation turn-by-turn", "prompt": "Nav on dash?" },
        { "keyword": "Phone mirroring", "prompt": "Mirror phone?" },
        { "keyword": "Weather display", "prompt": "Weather on dash?" },
        { "keyword": "Clock accuracy", "prompt": "Clock accurate?" }
      ]
    },
    {
      "topic": "Practical Use Cases (Commute/Delivery)",
      "entries": [
        { "keyword": "Commuter electric bike Vietnam", "prompt": "What is the maximum payload capacity suitable for delivery services for different electric bike models?" },
        { "keyword": "Electric delivery bike solutions", "prompt": "Do any electric scooters come with integrated racks or mounting points specifically designed for cargo boxes?" },
        { "keyword": "Sustainable urban transport Vietnam", "prompt": "Which electric motorcycle models are specifically designed for frequent stop-and-go city commuting?" },
        { "keyword": "Ground clearance EV", "prompt": "What is the ground clearance for various electric two-wheelers, suitable for navigating varied urban terrain?" },
        { "keyword": "Fleet management features", "prompt": "Are there electric bike models that offer connectivity features useful for fleet management or logistics?" },
        { "keyword": "GrabBike electric scooter", "prompt": "Is it profitable to run GrabBike using an electric scooter?" },
        { "keyword": "GoJek driver electric bike", "prompt": "Do GoJek drivers prefer electric bikes for fuel savings?" },
        { "keyword": "Delivery box mounting", "prompt": "Is it easy to install a delivery box on a VinFast Feliz?" },
        { "keyword": "Electric bike for food delivery", "prompt": "Which electric bike has the best range for all-day food delivery?" },
        { "keyword": "Commuting in Hanoi traffic", "prompt": "How does an electric bike perform in Hanoi's rush hour traffic?" },
        { "keyword": "Flooded street electric bike", "prompt": "Can I ride my electric scooter through flooded streets in Saigon?" },
        { "keyword": "Electric bike for students", "prompt": "What is the best electric bike for high school students?" },
        { "keyword": "Electric bike for office workers", "prompt": "Are electric scooters professional enough for office commuting?" },
        { "keyword": "Grocery shopping electric scooter", "prompt": "Does the floorboard have enough space for a bag of rice?" },
        { "keyword": "Picking up kids electric bike", "prompt": "Is the seat long enough to pick up two kids from school?" },
        { "keyword": "Long distance travel electric bike", "prompt": "Is it feasible to travel from Saigon to Vung Tau on an electric bike?" },
        { "keyword": "GrabExpress vehicle requirement", "prompt": "Does GrabExpress allow electric vehicles for goods delivery?" },
        { "keyword": "Ahamove driver electric bike", "prompt": "Are there specific incentives for Ahamove drivers using EVs?" },
        { "keyword": "Heavy load delivery scooter", "prompt": "Which electric scooter has the strongest rear rack for heavy loads?" },
        { "keyword": "Traffic jam maneuvering", "prompt": "Is the bike agile enough to weave through traffic jams?" },
        { "keyword": "Parking electric bike apartment", "prompt": "Do apartments charge extra for parking/charging electric bikes?" },
        { "keyword": "Portable battery for apartment", "prompt": "Which bikes allow charging the battery inside the apartment?" },
        { "keyword": "Electric bike for elderly", "prompt": "Are there electric tricycles suitable for elderly people?" },
        { "keyword": "Renting electric bike tourist", "prompt": "Where can tourists rent electric motorbikes in Hoi An?" },
        { "keyword": "Shared electric bike service", "prompt": "Are there any bike-sharing apps using electric scooters in Vietnam?" },
        { "keyword": "Pet transport electric bike", "prompt": "Is the floorboard wide enough to carry a pet dog?" },
        { "keyword": "Rainy season riding", "prompt": "Does the electric bike perform well in heavy monsoon rain?" },
        { "keyword": "Courier fleet electric", "prompt": "Which courier companies are switching to electric bike fleets?" },
        { "keyword": "Off-road capability", "prompt": "Can the bike handle dirt roads in rural areas?" },
        { "keyword": "Pothole durability", "prompt": "Can the suspension withstand constant potholes in industrial zones?" },
        { "keyword": "Daily mileage limit", "prompt": "Is there a recommended daily mileage limit for battery longevity?" },
        { "keyword": "Charging at workplace", "prompt": "Do office buildings commonly allow charging electric bikes in the basement?" },
        { "keyword": "Night riding visibility", "prompt": "Is the headlight strong enough for unlit country roads?" },
        { "keyword": "Weekend getaway range", "prompt": "Can I take the bike for a weekend trip to the outskirts?" },
        { "keyword": "Market shopping capacity", "prompt": "How many bags of groceries can I hang on the hooks?" },
        { "keyword": "University campus riding", "prompt": "Are e-bikes allowed on campus?" },
        { "keyword": "School drop off", "prompt": "Is it safe for school drop offs?" },
        { "keyword": "Hospital worker commute", "prompt": "Reliable for shift workers?" },
        { "keyword": "Construction site use", "prompt": "Rugged enough for sites?" },
        { "keyword": "Security guard patrol", "prompt": "Good for quiet patrols?" },
        { "keyword": "Postal delivery bike", "prompt": "Used by Vietnam Post?" },
        { "keyword": "Mobile coffee shop", "prompt": "Can it tow a small stall?" },
        { "keyword": "Fishing trip access", "prompt": "Can it reach remote spots?" },
        { "keyword": "Farm use electric bike", "prompt": "Useful on farms?" },
        { "keyword": "Resort transport", "prompt": "Used in resorts?" },
        { "keyword": "Airport staff transport", "prompt": "Used at airports?" },
        { "keyword": "Real estate agent viewings", "prompt": "Good for city viewings?" },
        { "keyword": "Photographer transport", "prompt": "Secure storage for gear?" },
        { "keyword": "Gym bag storage", "prompt": "Fits a gym bag?" },
        { "keyword": "Laptop transport safety", "prompt": "Safe to carry laptop?" },
        { "keyword": "Surfing board rack", "prompt": "Surfboard rack?" },
        { "keyword": "Golf bag carrier", "prompt": "Golf bag carrier?" },
        { "keyword": "Uber Moto electric", "prompt": "Uber Moto EV?" },
        { "keyword": "Baemin driver EV", "prompt": "Baemin EV?" },
        { "keyword": "FoodPanda EV", "prompt": "FoodPanda EV?" },
        { "keyword": "ShopeeFood EV", "prompt": "ShopeeFood EV?" },
        { "keyword": "Lalamove EV", "prompt": "Lalamove EV?" },
        { "keyword": "Ninjavans EV", "prompt": "Ninjavans EV?" },
        { "keyword": "J&T Express EV", "prompt": "J&T EV?" },
        { "keyword": "DHL EV fleet", "prompt": "DHL fleet?" },
        { "keyword": "FedEx EV fleet", "prompt": "FedEx fleet?" },
        { "keyword": "Highlands Coffee delivery", "prompt": "Highlands delivery?" },
        { "keyword": "Phuc Long delivery", "prompt": "Phuc Long delivery?" },
        { "keyword": "Pizza Hut delivery", "prompt": "Pizza delivery?" },
        { "keyword": "KFC delivery bike", "prompt": "KFC bike?" },
        { "keyword": "Lotteria delivery", "prompt": "Lotteria delivery?" },
        { "keyword": "Flower delivery EV", "prompt": "Flower delivery?" },
        { "keyword": "Laundry service pickup", "prompt": "Laundry pickup?" },
        { "keyword": "Maid service transport", "prompt": "Maid transport?" },
        { "keyword": "Tutor transport", "prompt": "Tutor transport?" },
        { "keyword": "Electric police bike", "prompt": "Police bike?" },
        { "keyword": "Electric ambulance bike", "prompt": "Ambulance bike?" },
        { "keyword": "Firefighter scout bike", "prompt": "Fire scout?" },
        { "keyword": "Park ranger bike", "prompt": "Park ranger?" },
        { "keyword": "Campus security bike", "prompt": "Campus security?" },
        { "keyword": "Factory floor transport", "prompt": "Factory transport?" },
        { "keyword": "Warehouse transport", "prompt": "Warehouse transport?" },
        { "keyword": "Port terminal transport", "prompt": "Port transport?" },
        { "keyword": "Event staff transport", "prompt": "Event staff?" },
        { "keyword": "Film crew scout", "prompt": "Film scout?" }
      ]
    },
    {
      "topic": "Government Support and Incentives",
      "entries": [
        { "keyword": "Government incentives EV Vietnam", "prompt": "Are there specific electric bike models that currently qualify for government subsidies or purchase incentives?" },
        { "keyword": "EV bike registration Vietnam", "prompt": "What are the current tax exemptions or reductions applicable to various electric two-wheelers in Vietnam?" },
        { "keyword": "Priority access EV", "prompt": "Do any electric scooter models benefit from priority access or special lanes in specific urban zones?" },
        { "keyword": "Claiming government benefits", "prompt": "What documentation is required to claim any available government benefits for electric motorcycle purchases?" },
        { "keyword": "Local province initiatives", "prompt": "Are there local initiatives in specific provinces that support the adoption of certain electric bike types?" },
        { "keyword": "Registration fee exemption EV", "prompt": "Is the registration fee 100% waived for electric motorcycles in 2024?" },
        { "keyword": "Special consumption tax EV", "prompt": "How does the special consumption tax reduction affect EV bike prices?" },
        { "keyword": "Green energy subsidy Vietnam", "prompt": "Does the government offer cash subsidies for buying green vehicles?" },
        { "keyword": "Free parking for EV", "prompt": "Are there public parking lots that are free for electric vehicles?" },
        { "keyword": "Bus lane access EV", "prompt": "Is there any discussion about allowing EVs to use bus lanes?" },
        { "keyword": "Government fleet electric transition", "prompt": "Is the Vietnamese government transitioning its official fleet to electric bikes?" },
        { "keyword": "EV manufacturing incentives", "prompt": "What incentives do manufacturers like VinFast receive to produce EVs?" },
        { "keyword": "Battery recycling policy", "prompt": "Are there government regulations ensuring safe battery disposal?" },
        { "keyword": "Carbon credit Vietnam EV", "prompt": "Can companies earn carbon credits by using electric delivery fleets?" },
        { "keyword": "Clean air initiative Hanoi", "prompt": "How does the Hanoi clean air plan impact motorcycle restrictions?" },
        { "keyword": "Smart city electric transport", "prompt": "What is the role of electric bikes in Vietnam's smart city planning?" },
        { "keyword": "Tax reduction for EV assembly", "prompt": "Do assembled-in-Vietnam EVs get tax breaks on imported parts?" },
        { "keyword": "Import duty electric components", "prompt": "Are import duties lower for electric motor parts compared to engines?" },
        { "keyword": "Charging infrastructure support", "prompt": "Does the government subsidize the installation of public charging stations?" },
        { "keyword": "Public awareness campaign EV", "prompt": "Are there official campaigns promoting the benefits of electric mobility?" },
        { "keyword": "Student subsidy electric bike", "prompt": "Are there any proposed subsidies for students to buy electric bikes?" },
        { "keyword": "Trade-in support old moto", "prompt": "Is there a government program to scrap old motorbikes for EVs?" },
        { "keyword": "Low interest loan green vehicle", "prompt": "Do state banks offer lower interest rates for EV loans?" },
        { "keyword": "Future ban on gas motorcycles", "prompt": "When does Vietnam plan to ban gasoline motorcycles in city centers?" },
        { "keyword": "Zero emission zone Hanoi", "prompt": "Which districts in Hanoi are planned to become zero-emission zones?" },
        { "keyword": "COP26 Vietnam commitment", "prompt": "How does the electric bike adoption fit into Vietnam's COP26 commitments?" },
        { "keyword": "National Green Growth Strategy", "prompt": "Is electric mobility a key pillar of the National Green Growth Strategy?" },
        { "keyword": "Electric taxi support", "prompt": "Are there specific incentives for electric motorcycle taxi companies?" },
        { "keyword": "Renewable energy charging", "prompt": "Are there incentives for charging stations powered by solar energy?" },
        { "keyword": "Government tender EV", "prompt": "Are there open government tenders for supplying electric bikes to the police?" },
        { "keyword": "Start-up grants EV sector", "prompt": "Are there grants available for startups in the electric vehicle ecosystem?" },
        { "keyword": "Standardization of charging", "prompt": "Is the government enforcing a standard charging connector for all bikes?" },
        { "keyword": "Electricity price for EV charging", "prompt": "Is there a special electricity tariff for charging operators?" },
        { "keyword": "Restriction on old motorbikes", "prompt": "Will old petrol motorbikes be restricted from entering certain areas?" },
        { "keyword": "Safety standard enforcement", "prompt": "Is the government tightening safety standards for imported electric scooters?" },
        { "keyword": "Policy roadmap EV 2030", "prompt": "What is the policy roadmap for 2030?" },
        { "keyword": "Net Zero 2050 Vietnam", "prompt": "Contribution to Net Zero 2050?" },
        { "keyword": "Foreign investment EV sector", "prompt": "Incentives for foreign investors?" },
        { "keyword": "Local content requirement", "prompt": "Are there local content requirements?" },
        { "keyword": "Battery production incentive", "prompt": "Incentives for battery plants?" },
        { "keyword": "Charging station permit", "prompt": "Permits for charging stations?" },
        { "keyword": "Grid impact study", "prompt": "Studies on grid impact?" },
        { "keyword": "Urban planning EV", "prompt": "EVs in urban planning?" },
        { "keyword": "Public transport integration", "prompt": "Integration with public transport?" },
        { "keyword": "Green license plate proposal", "prompt": "Proposal for green plates?" },
        { "keyword": "Congestion charge exemption", "prompt": "Exemption from congestion charges?" },
        { "keyword": "Reduced toll fees", "prompt": "Reduced tolls for EVs?" },
        { "keyword": "Eco-label certification", "prompt": "Eco-labeling for bikes?" },
        { "keyword": "R&D grants EV", "prompt": "Grants for R&D?" },
        { "keyword": "Vocational training EV", "prompt": "Training for EV mechanics?" },
        { "keyword": "Import tax CBU EV", "prompt": "Import tax on CBU?" },
        { "keyword": "VAT reduction EV", "prompt": "VAT reduction?" },
        { "keyword": "Corporate tax incentive EV", "prompt": "Corporate tax break?" },
        { "keyword": "Land rental incentive", "prompt": "Land rental break?" },
        { "keyword": "Technology transfer incentive", "prompt": "Tech transfer help?" },
        { "keyword": "Intellectual property support", "prompt": "IP support?" },
        { "keyword": "Export credit support", "prompt": "Export credit?" },
        { "keyword": "Green bond financing", "prompt": "Green bonds?" },
        { "keyword": "Sustainability reporting", "prompt": "Sustainability report?" },
        { "keyword": "ESG compliance EV", "prompt": "ESG compliance?" },
        { "keyword": "Carbon footprint labeling", "prompt": "Carbon labeling?" },
        { "keyword": "Right to repair legislation", "prompt": "Right to repair?" },
        { "keyword": "Consumer protection EV", "prompt": "Consumer protection?" },
        { "keyword": "Data privacy EV app", "prompt": "Data privacy?" },
        { "keyword": "Cybersecurity standard EV", "prompt": "Cybersecurity?" },
        { "keyword": "Homologation standard", "prompt": "Homologation?" },
        { "keyword": "Crash test requirement", "prompt": "Crash test rules?" },
        { "keyword": "Noise pollution regulation", "prompt": "Noise regulation?" },
        { "keyword": "EMC standard EV", "prompt": "EMC standard?" },
        { "keyword": "Battery transport regulation", "prompt": "Battery transport?" },
        { "keyword": "Fire safety code charging", "prompt": "Fire code?" },
        { "keyword": "Building code EV ready", "prompt": "Building code?" }
      ]
    }
  ]
};